import { MigrationInterface, QueryRunner, Table, TableColumn, TableForeignKey, TableIndex } from 'typeorm';

const FIX_COLUMN = 'customFields__fix_relational_custom_fields__';
const FIX_COMMENT = 'A work-around needed when only relational custom fields are defined on an entity';

export class AddBadgesToCollectionAndPromotion1776186352167 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        // --- Collection.badges (list: true) → junction table ---
        await queryRunner.createTable(
            new Table({
                name: 'collection_custom_fields_badges_badge',
                columns: [
                    { name: 'collectionId', type: 'int', isPrimary: true },
                    { name: 'badgeId', type: 'int', isPrimary: true },
                ],
                indices: [
                    new TableIndex({ columnNames: ['collectionId'] }),
                    new TableIndex({ columnNames: ['badgeId'] }),
                ],
                foreignKeys: [
                    new TableForeignKey({
                        columnNames: ['collectionId'],
                        referencedTableName: 'collection',
                        referencedColumnNames: ['id'],
                        onDelete: 'CASCADE',
                        onUpdate: 'CASCADE',
                    }),
                    new TableForeignKey({
                        columnNames: ['badgeId'],
                        referencedTableName: 'badge',
                        referencedColumnNames: ['id'],
                        onDelete: 'CASCADE',
                        onUpdate: 'CASCADE',
                    }),
                ],
            }),
        );

        // --- Fix columns: collection and collection_translation ---
        await queryRunner.addColumn(
            'collection_translation',
            new TableColumn({ name: FIX_COLUMN, type: 'tinyint', isNullable: true, comment: FIX_COMMENT }),
        );
        await queryRunner.addColumn(
            'collection',
            new TableColumn({ name: FIX_COLUMN, type: 'tinyint', isNullable: true, comment: FIX_COMMENT }),
        );

        // --- Fix columns: promotion and promotion_translation ---
        await queryRunner.addColumn(
            'promotion_translation',
            new TableColumn({ name: FIX_COLUMN, type: 'tinyint', isNullable: true, comment: FIX_COMMENT }),
        );
        await queryRunner.addColumn(
            'promotion',
            new TableColumn({ name: FIX_COLUMN, type: 'tinyint', isNullable: true, comment: FIX_COMMENT }),
        );

        // --- Promotion.badge (list: false) → FK column on promotion table ---
        // Column name is 'customFieldsBadgeid' — exact name generated by Vendure/TypeORM
        await queryRunner.addColumn(
            'promotion',
            new TableColumn({ name: 'customFieldsBadgeid', type: 'int', isNullable: true }),
        );
        await queryRunner.createForeignKey(
            'promotion',
            new TableForeignKey({
                columnNames: ['customFieldsBadgeid'],
                referencedTableName: 'badge',
                referencedColumnNames: ['id'],
                onDelete: 'SET NULL',  // safe: deleting a badge just clears the promotion association
                onUpdate: 'NO ACTION',
            }),
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Drop promotion FK and column
        const promotionTable = await queryRunner.getTable('promotion');
        const promotionFK = promotionTable?.foreignKeys.find(fk => fk.columnNames.includes('customFieldsBadgeid'));
        if (promotionFK) {
            await queryRunner.dropForeignKey('promotion', promotionFK);
        }
        if (await queryRunner.hasColumn('promotion', 'customFieldsBadgeid')) {
            await queryRunner.dropColumn('promotion', 'customFieldsBadgeid');
        }

        // Drop fix columns
        if (await queryRunner.hasColumn('promotion', FIX_COLUMN)) {
            await queryRunner.dropColumn('promotion', FIX_COLUMN);
        }
        if (await queryRunner.hasColumn('promotion_translation', FIX_COLUMN)) {
            await queryRunner.dropColumn('promotion_translation', FIX_COLUMN);
        }
        if (await queryRunner.hasColumn('collection', FIX_COLUMN)) {
            await queryRunner.dropColumn('collection', FIX_COLUMN);
        }
        if (await queryRunner.hasColumn('collection_translation', FIX_COLUMN)) {
            await queryRunner.dropColumn('collection_translation', FIX_COLUMN);
        }

        // Drop collection junction table
        await queryRunner.dropTable('collection_custom_fields_badges_badge');
    }
}
