name: Deploy Frontend (Next.js)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-frontend
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]  # que coincida con los labels de tu runner

    env:
      COMPOSE_PROJECT_NAME: next_frontend
      BASE_DIR: /home/cla

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker versions
        run: |
          docker version
          docker compose version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copiar .env.production del VPS
        run: |
          if [ -f "$BASE_DIR/env/front/.env.production" ]; then
            cp "$BASE_DIR/env/front/.env.production" .env.production
          else
            echo "No se encontró $BASE_DIR/env/front/.env.production"; exit 1
          fi

      - name: Build & Deploy (puerto 3200)
        run: |
          docker compose down --remove-orphans || true
          docker compose build --no-cache
          docker compose up -d

      - name: Limpiar imágenes viejas
        run: docker image prune -f
